general.import = [
	"~/.config/alacritty/colors/suckless-blue.toml",
]

general.live_config_reload = true

[env]

[window]
dimensions = { columns = 40, lines = 40 }
position = "None"
padding = { x = 2, y = 1 }
dynamic_padding = false
decorations = "None"  # Options: "Full" | "None" | "Buttonless"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Λ"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "TX-02", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 18
offset = { x = 1, y = 0 }  # Default: x = 0, y = 0
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
builtin_box_drawing = true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[bell]
animation = "Linear"
duration = 0 
color = "#ffffff"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

[keyboard]
bindings = [
	{ key = "T", mods = "Command",  action = "None" },
	# { key = "Key", mods = "Modifiers", action = "Action" },
	# { key = "Key", mods = "Modifiers", chars = "Characters to send" },
	# ...
]
