import = [
	"~/.config/alacritty/colors/suckless-blue.toml",
]

live_config_reload = true  # Default: true

[env]

[window]
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0
position = "None"  # Default: "None"
padding = { x = 4, y = 4 }  # Default: x = 0, y = 0
dynamic_padding = false  # Default: false
decorations = "Buttonless"  # Options: "Full" | "None" | "Buttonless"
opacity = 1.0  # Default: 1.0
blur = false # Default: false
startup_mode = "Windowed"  # Default: "Windowed"
title = "Λ"
dynamic_title = true  # Default: true
class = { instance = "Alacritty", general = "Alacritty" }  # Default: instance = "Alacritty", general = "Alacritty"
decorations_theme_variant = "None"  # Default: "None"
resize_increments = false  # Default: false
option_as_alt = "Both"  # Default: "None"

[scrolling]
history = 10000  # Default: 10000
multiplier = 3  # Default: 3

[font]
normal = { family = "Berkeley Mono Variable", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
size = 16
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
builtin_box_drawing = true  # Default: true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[bell]
animation = "Linear"  # Default: "Linear"
duration = 0  # Default: 0
color = "#ffffff"  # Default: "#ffffff"
command = "None"  # Default: "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false  # Default: false

[cursor]
style = { shape = "Block", blinking = "Off" }  # Default: shape = "Block", blinking = "Off"
vi_mode_style = "None"  # Default: "None"
blink_interval = 750  # Default: 750
blink_timeout = 0  # Default: 5
unfocused_hollow = true  # Default: true
thickness = 0.15  # Default: 0.15

[terminal]
osc52 = "CopyPaste"  # Default: "OnlyCopy"

[mouse]
hide_when_typing = true  # Default: false
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

[keyboard]
bindings = [
	# { key = "Key", mods = "Modifiers", action = "Action" },
	# { key = "Key", mods = "Modifiers", chars = "Characters to send" },
	# ...
]
