#!/usr/bin/env bash

./configs/defaults.sh

# LEFT
./configs/layout-type.sh
./configs/spaces.sh
./configs/focus.sh
./configs/modal.sh

# RIGHT
./configs/time.sh
./configs/battery.sh
./configs/volume.sh

sketchybar --update
